[package]
name = "kette-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { path = "../parser" }
tokio = { version = "1.48.0", features = ["io-std", "macros", "rt-multi-thread", "sync", "time"] }
tower-lsp = "0.20.0"
url = "2.5.7"
